### PR TITLE
Upgrade cucumber gherkin to v12

### PR DESCRIPTION
**Pull request by jayzz55**
gherkin-ruby released v12 here: https://github.com/cucumber/gherkin-ruby/releases/tag/v12.0.0

this commit is to update dependency to use the latest version of
cucumber gherkin.

### CODE REVIEW

**Comment by jayzz55** [comment]
Not sure why the CI build is failing on `uninitialized constant Pry::Command::ExitAll` for ruby with version 2.3.6

Currently trying to debug and fix this.

**Comment by gongo** [comment]
Hi @jayzz55 

I have removed 2.3 and 2.4 from `.travis.yml. (Both were EOL)

https://github.com/jnicklas/turnip/pull/225

**Comment by jayzz55** [comment]
Sweet, thank you @gongo :-)

**Comment by gongo** [comment]
Thanks!

**Pull request merged**
