### PR TITLE
Added support for more BDD file extensions.

### PR DESCRIPTION
**Pull request by jnyman**

### CODE REVIEW

**Comment by gongo** [comment]
Thanks for propose.

I did not know that `.story` and `.spec` are commonly used for BDD-style file in the world.
Do you have any (usage) example or documentation of that extensions?

If these are not commonly, I think should support `.feature` only one.

**Comment by jnyman** [comment]
This request was mostly because just about every place I have worked has asked for the ability to not be forced into using just `.feature` as the extension. And this is because not every such file is a "feature," per se. So allowing more options, in my view, allows more flexibility for people to conceptualize the work artifacts as they choose rather than forcing them to adhere to what was simply an artifact of the Cucumber process.

So this is not so much supporting what other tools do; it's more meant to suggest support for the common language that people use to talk about various artifacts and conceptualize those artifacts as discrete units of work.

Some tools have ventured into this territory. For example, the tool jBehave, as one example, uses the `.story` extension. I realize that's a Java tool and this is a Ruby one but the reason they chose that extension is because much of what you are writing with business is a "story" in terms of how business analysts look at it. As far as the `.spec` extension, admittedly not too many tools use it but it is very common in BDD shops to use the term "test specification" -- or even just a "specification" -- for what Cucumber calls "feature files."

So, again, just to make the rationale clear: it's possible to conceptualize these artifacts in different ways: stories, specs, and, perhaps, features. This proposed change allows users to use any one of these as they wish, which can further help them break down their repository organization. For example, I've had some shops that use high-level features (with `.feature` files) and then have a further breakdown of technical specifications and UI elements (with `.spec` files).

**Comment by gongo** [comment]
@jnyman Thank you for you comment.

But, I still think should support `.feature` only one.

## 1st

> Turnip is a **Gherkin extension** for RSpec
>
> via [README.md](https://github.com/jnicklas/turnip/blob/master/README.md)

---

> Source files have **.feature extension** .
>
> via [Gherkin · cucumber/cucumber Wiki](https://github.com/cucumber/cucumber/wiki/Gherkin)

## 2nd

> So, again, just to make the rationale clear: it's possible to conceptualize these artifacts in different ways: stories, specs, and, perhaps, features. This proposed change allows users to use any one of these as they wish, which can further help them break down their repository organization.

I understand your point. But, these are not in turnip territory.
Turnip is **just** a Gherkin extension.

1. Read `.feature`
1. Relation to ruby methods
    - `When foo` -> `step foo do ; end`
1. execute ruby methods

That's all !

If you want to split them, put the difference in the structure of the directory (**not the file exetnsion**)
```
(direcotory)
  |-- features
  |   `-- foo.feature
  |-- specs
  |   `-- bar.feature
  `-- stories
      `-- baz.feature
```

**Comment by jnyman** [comment]
I respect that decision and I understand it. I will likely have to create a tool similar to Turnip to support this because right now there are way too many places (Oracle included, I might add) that generally won't use tools that don't allow them to utilize these test artifacts in a way that they feel best suits their business needs.

I appreciate you engaging with me on the rationale for your thoughts and, as I said, I entirely respect the decision. I'll close this particular request out.

**Pull request closed without merging**
